name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - id: auth
      name: Authorize Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '432.0.0'

    - name: Deploy
      run: > 
        gcloud
        functions
        deploy
        helloHttp
        --project=${{ secrets.GCP_PROJECT_ID }}
        --region=us-east1
        --runtime=nodejs16
        --gen2
        --trigger-http
        --allow-unauthenticated